image: crystallang/crystal:latest-alpine

stages:
  - test
  - deploy

spec:
  stage: test
  before_script:
    - crystal --version
    - shards --version
    - shards install
  script:
    - crystal bin/ameba.cr
    - crystal spec --error-trace
    - crystal doc
    - mv docs public
  artifacts:
    paths: [public]

pages:
  stage: deploy
  script:
    - "true"
  artifacts:
    paths: [public]
  only: [master]
